// Code generated by qtc from "nav.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line nav.qtpl:1
package bootstrapper

//line nav.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line nav.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line nav.qtpl:1
func StreamNavbarHtml(qw422016 *qt422016.Writer, navData Navbar) {
//line nav.qtpl:1
	qw422016.N().S(`
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="`)
//line nav.qtpl:3
	qw422016.E().S(navData.Title.Href)
//line nav.qtpl:3
	qw422016.N().S(`">`)
//line nav.qtpl:3
	qw422016.E().S(navData.Title.InnerHTML)
//line nav.qtpl:3
	qw422016.N().S(`</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">

`)
//line nav.qtpl:11
	for _, link := range navData.MenuLinks {
//line nav.qtpl:11
		qw422016.N().S(`
  `)
//line nav.qtpl:12
		if len(link.SubLinks) == 0 {
//line nav.qtpl:12
			qw422016.N().S(`
    `)
//line nav.qtpl:13
			if len(link.Href) > 0 {
//line nav.qtpl:13
				qw422016.N().S(`
      `)
//line nav.qtpl:14
				if link.Current {
//line nav.qtpl:14
					qw422016.N().S(`
      <li class="nav-item active">
        <a class="nav-link" href="`)
//line nav.qtpl:16
					qw422016.E().S(link.Href)
//line nav.qtpl:16
					qw422016.N().S(`">`)
//line nav.qtpl:16
					qw422016.E().S(link.InnerHTML)
//line nav.qtpl:16
					qw422016.N().S(` <span class="sr-only">(current)</span></a>
      </li>
      `)
//line nav.qtpl:18
				} else {
//line nav.qtpl:18
					qw422016.N().S(`
      <li class="nav-item">
        <a class="nav-link" href="`)
//line nav.qtpl:20
					qw422016.E().S(link.Href)
//line nav.qtpl:20
					qw422016.N().S(`">`)
//line nav.qtpl:20
					qw422016.E().S(link.InnerHTML)
//line nav.qtpl:20
					qw422016.N().S(`</a>
      </li>
      `)
//line nav.qtpl:22
				}
//line nav.qtpl:22
				qw422016.N().S(`
    `)
//line nav.qtpl:23
			} else {
//line nav.qtpl:23
				qw422016.N().S(`
      <li class="nav-item">`)
//line nav.qtpl:24
				qw422016.E().S(link.InnerHTML)
//line nav.qtpl:24
				qw422016.N().S(`</li>
    `)
//line nav.qtpl:25
			}
//line nav.qtpl:25
			qw422016.N().S(`
  `)
//line nav.qtpl:26
		} else {
//line nav.qtpl:26
			qw422016.N().S(`
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="`)
//line nav.qtpl:28
			qw422016.E().S(link.Href)
//line nav.qtpl:28
			qw422016.N().S(`" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">`)
//line nav.qtpl:28
			qw422016.E().S(link.InnerHTML)
//line nav.qtpl:28
			qw422016.N().S(`</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          `)
//line nav.qtpl:30
			for _, sublink := range link.SubLinks {
//line nav.qtpl:30
				qw422016.N().S(`
          <a class="dropdown-item" href="`)
//line nav.qtpl:31
				qw422016.E().S(sublink.Href)
//line nav.qtpl:31
				qw422016.N().S(`">`)
//line nav.qtpl:31
				qw422016.E().S(sublink.InnerHTML)
//line nav.qtpl:31
				qw422016.N().S(`</a>
          `)
//line nav.qtpl:32
			}
//line nav.qtpl:32
			qw422016.N().S(`
        </div>
      </li>
  `)
//line nav.qtpl:35
		}
//line nav.qtpl:35
		qw422016.N().S(`
`)
//line nav.qtpl:36
	}
//line nav.qtpl:36
	qw422016.N().S(`
    </ul>
    <form class="form-inline my-2 my-lg-0" action="`)
//line nav.qtpl:38
	qw422016.E().S(navData.Search.Action)
//line nav.qtpl:38
	qw422016.N().S(`" method="`)
//line nav.qtpl:38
	qw422016.E().S(navData.Search.Method)
//line nav.qtpl:38
	qw422016.N().S(`">
      <input class="form-control mr-sm-2" type="text" placeholder="`)
//line nav.qtpl:39
	qw422016.E().S(navData.Search.Placeholder)
//line nav.qtpl:39
	qw422016.N().S(`" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">`)
//line nav.qtpl:40
	qw422016.E().S(navData.Search.Text)
//line nav.qtpl:40
	qw422016.N().S(`</button>
    </form>
  </div>
</nav>
`)
//line nav.qtpl:44
}

//line nav.qtpl:44
func WriteNavbarHtml(qq422016 qtio422016.Writer, navData Navbar) {
//line nav.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line nav.qtpl:44
	StreamNavbarHtml(qw422016, navData)
//line nav.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line nav.qtpl:44
}

//line nav.qtpl:44
func NavbarHtml(navData Navbar) string {
//line nav.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line nav.qtpl:44
	WriteNavbarHtml(qb422016, navData)
//line nav.qtpl:44
	qs422016 := string(qb422016.B)
//line nav.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line nav.qtpl:44
	return qs422016
//line nav.qtpl:44
}
